// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $account_feedback from "./routes/account/feedback.tsx";
import * as $account_settings from "./routes/account/settings.tsx";
import * as $admin_middleware from "./routes/admin/_middleware.ts";
import * as $admin_activity from "./routes/admin/activity.tsx";
import * as $admin_admin_panel from "./routes/admin/admin-panel.tsx";
import * as $admin_backup from "./routes/admin/backup.ts";
import * as $admin_cleanup from "./routes/admin/cleanup.ts";
import * as $admin_clear_db from "./routes/admin/clear-db.ts";
import * as $admin_export_json from "./routes/admin/export-json.ts";
import * as $admin_export_templates_json from "./routes/admin/export-templates-json.ts";
import * as $admin_export from "./routes/admin/export.ts";
import * as $admin_feedback from "./routes/admin/feedback.tsx";
import * as $admin_import_templates from "./routes/admin/import-templates.ts";
import * as $admin_import from "./routes/admin/import.ts";
import * as $admin_notify from "./routes/admin/notify.ts";
import * as $admin_rebuild_indexes from "./routes/admin/rebuild-indexes.ts";
import * as $admin_restore_backup from "./routes/admin/restore-backup.ts";
import * as $admin_stocktake from "./routes/admin/stocktake.tsx";
import * as $api_camp_templates_id_ from "./routes/api/camp-templates/[id].ts";
import * as $api_camp_templates_index from "./routes/api/camp-templates/index.ts";
import * as $api_camps_id_ from "./routes/api/camps/[id].ts";
import * as $api_camps_index from "./routes/api/camps/index.ts";
import * as $api_easter_egg from "./routes/api/easter-egg.ts";
import * as $api_feedback_photos from "./routes/api/feedback-photos.ts";
import * as $api_feedback_photos_photoId_ from "./routes/api/feedback-photos/[photoId].ts";
import * as $api_feedback_pending_count from "./routes/api/feedback/pending-count.ts";
import * as $api_first_aid_check from "./routes/api/first-aid-check.ts";
import * as $api_items_id_ from "./routes/api/items/[id].ts";
import * as $api_items_id_photo from "./routes/api/items/[id]/photo.ts";
import * as $api_items_id_photos_photoId_ from "./routes/api/items/[id]/photos/[photoId].ts";
import * as $api_items_id_photos_index from "./routes/api/items/[id]/photos/index.ts";
import * as $api_items_index from "./routes/api/items/index.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_loans_id_ from "./routes/api/loans/[id].ts";
import * as $api_loans_index from "./routes/api/loans/index.ts";
import * as $api_logout from "./routes/api/logout.ts";
import * as $api_meals_id_ from "./routes/api/meals/[id].ts";
import * as $api_meals_index from "./routes/api/meals/index.ts";
import * as $api_neckers from "./routes/api/neckers.ts";
import * as $api_ping from "./routes/api/ping.ts";
import * as $api_stats from "./routes/api/stats.ts";
import * as $api_stocktake from "./routes/api/stocktake.ts";
import * as $camps_id_ from "./routes/camps/[id].tsx";
import * as $camps_id_edit from "./routes/camps/[id]/edit.tsx";
import * as $camps_id_print from "./routes/camps/[id]/print.tsx";
import * as $camps_index from "./routes/camps/index.tsx";
import * as $camps_new from "./routes/camps/new.tsx";
import * as $camps_templates from "./routes/camps/templates.tsx";
import * as $first_aid_catalog from "./routes/first-aid/catalog.tsx";
import * as $first_aid_check from "./routes/first-aid/check.tsx";
import * as $first_aid_index from "./routes/first-aid/index.tsx";
import * as $first_aid_print from "./routes/first-aid/print.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $inventory_id_ from "./routes/inventory/[id].tsx";
import * as $inventory_id_maintenance from "./routes/inventory/[id]/maintenance.tsx";
import * as $inventory_id_qr from "./routes/inventory/[id]/qr.tsx";
import * as $inventory_id_scan from "./routes/inventory/[id]/scan.tsx";
import * as $inventory_add from "./routes/inventory/add.tsx";
import * as $inventory_edit_id_ from "./routes/inventory/edit/[id].tsx";
import * as $inventory_index from "./routes/inventory/index.tsx";
import * as $loans_index from "./routes/loans/index.tsx";
import * as $loans_new from "./routes/loans/new.tsx";
import * as $login from "./routes/login.tsx";
import * as $meals_id_edit from "./routes/meals/[id]/edit.tsx";
import * as $meals_index from "./routes/meals/index.tsx";
import * as $meals_new from "./routes/meals/new.tsx";
import * as $neckers from "./routes/neckers.tsx";
import * as $reports_expiring from "./routes/reports/expiring.tsx";
import * as $risk_assessments_id_edit from "./routes/risk-assessments/[id]/edit.tsx";
import * as $risk_assessments_index from "./routes/risk-assessments/index.tsx";
import * as $risk_assessments_print from "./routes/risk-assessments/print.tsx";
import * as $BackupButtons from "./islands/BackupButtons.tsx";
import * as $BulkImport from "./islands/BulkImport.tsx";
import * as $CampCalendar from "./islands/CampCalendar.tsx";
import * as $CampChecklist from "./islands/CampChecklist.tsx";
import * as $CampPlanForm from "./islands/CampPlanForm.tsx";
import * as $CampPlanList from "./islands/CampPlanList.tsx";
import * as $ConfirmDeleteForm from "./islands/ConfirmDeleteForm.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $DbCleanup from "./islands/DbCleanup.tsx";
import * as $DbClear from "./islands/DbClear.tsx";
import * as $EasterEgg from "./islands/EasterEgg.tsx";
import * as $FeedbackFormClient from "./islands/FeedbackFormClient.tsx";
import * as $FeedbackPendingBadge from "./islands/FeedbackPendingBadge.tsx";
import * as $FeedbackScreenshot from "./islands/FeedbackScreenshot.tsx";
import * as $FirstAidCheckWizard from "./islands/FirstAidCheckWizard.tsx";
import * as $FirstAidKitEditor from "./islands/FirstAidKitEditor.tsx";
import * as $InventoryTable from "./islands/InventoryTable.tsx";
import * as $ItemDeleteButton from "./islands/ItemDeleteButton.tsx";
import * as $ItemForm from "./islands/ItemForm.tsx";
import * as $LoanForm from "./islands/LoanForm.tsx";
import * as $LoanList from "./islands/LoanList.tsx";
import * as $MealForm from "./islands/MealForm.tsx";
import * as $MealPlannerForm from "./islands/MealPlannerForm.tsx";
import * as $MobileNav from "./islands/MobileNav.tsx";
import * as $NeckerAlert from "./islands/NeckerAlert.tsx";
import * as $NeckerCounter from "./islands/NeckerCounter.tsx";
import * as $NeckerDashboard from "./islands/NeckerDashboard.tsx";
import * as $NotificationButtons from "./islands/NotificationButtons.tsx";
import * as $PasswordInput from "./islands/PasswordInput.tsx";
import * as $PhotoUpload from "./islands/PhotoUpload.tsx";
import * as $PhotoViewer from "./islands/PhotoViewer.tsx";
import * as $PrintButton from "./islands/PrintButton.tsx";
import * as $RebuildIndexes from "./islands/RebuildIndexes.tsx";
import * as $RestoreBackupForm from "./islands/RestoreBackupForm.tsx";
import * as $RiskAssessmentForm from "./islands/RiskAssessmentForm.tsx";
import * as $SpaceDashboard from "./islands/SpaceDashboard.tsx";
import * as $StocktakeWizard from "./islands/StocktakeWizard.tsx";
import * as $TemplateAppendForm from "./islands/TemplateAppendForm.tsx";
import * as $TemplateBuilder from "./islands/TemplateBuilder.tsx";
import * as $TemplateBulkImport from "./islands/TemplateBulkImport.tsx";
import * as $ThemeToggle from "./islands/ThemeToggle.tsx";
import * as $UserDirectory from "./islands/UserDirectory.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/account/feedback.tsx": $account_feedback,
    "./routes/account/settings.tsx": $account_settings,
    "./routes/admin/_middleware.ts": $admin_middleware,
    "./routes/admin/activity.tsx": $admin_activity,
    "./routes/admin/admin-panel.tsx": $admin_admin_panel,
    "./routes/admin/backup.ts": $admin_backup,
    "./routes/admin/cleanup.ts": $admin_cleanup,
    "./routes/admin/clear-db.ts": $admin_clear_db,
    "./routes/admin/export-json.ts": $admin_export_json,
    "./routes/admin/export-templates-json.ts": $admin_export_templates_json,
    "./routes/admin/export.ts": $admin_export,
    "./routes/admin/feedback.tsx": $admin_feedback,
    "./routes/admin/import-templates.ts": $admin_import_templates,
    "./routes/admin/import.ts": $admin_import,
    "./routes/admin/notify.ts": $admin_notify,
    "./routes/admin/rebuild-indexes.ts": $admin_rebuild_indexes,
    "./routes/admin/restore-backup.ts": $admin_restore_backup,
    "./routes/admin/stocktake.tsx": $admin_stocktake,
    "./routes/api/camp-templates/[id].ts": $api_camp_templates_id_,
    "./routes/api/camp-templates/index.ts": $api_camp_templates_index,
    "./routes/api/camps/[id].ts": $api_camps_id_,
    "./routes/api/camps/index.ts": $api_camps_index,
    "./routes/api/easter-egg.ts": $api_easter_egg,
    "./routes/api/feedback-photos.ts": $api_feedback_photos,
    "./routes/api/feedback-photos/[photoId].ts": $api_feedback_photos_photoId_,
    "./routes/api/feedback/pending-count.ts": $api_feedback_pending_count,
    "./routes/api/first-aid-check.ts": $api_first_aid_check,
    "./routes/api/items/[id].ts": $api_items_id_,
    "./routes/api/items/[id]/photo.ts": $api_items_id_photo,
    "./routes/api/items/[id]/photos/[photoId].ts":
      $api_items_id_photos_photoId_,
    "./routes/api/items/[id]/photos/index.ts": $api_items_id_photos_index,
    "./routes/api/items/index.ts": $api_items_index,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/loans/[id].ts": $api_loans_id_,
    "./routes/api/loans/index.ts": $api_loans_index,
    "./routes/api/logout.ts": $api_logout,
    "./routes/api/meals/[id].ts": $api_meals_id_,
    "./routes/api/meals/index.ts": $api_meals_index,
    "./routes/api/neckers.ts": $api_neckers,
    "./routes/api/ping.ts": $api_ping,
    "./routes/api/stats.ts": $api_stats,
    "./routes/api/stocktake.ts": $api_stocktake,
    "./routes/camps/[id].tsx": $camps_id_,
    "./routes/camps/[id]/edit.tsx": $camps_id_edit,
    "./routes/camps/[id]/print.tsx": $camps_id_print,
    "./routes/camps/index.tsx": $camps_index,
    "./routes/camps/new.tsx": $camps_new,
    "./routes/camps/templates.tsx": $camps_templates,
    "./routes/first-aid/catalog.tsx": $first_aid_catalog,
    "./routes/first-aid/check.tsx": $first_aid_check,
    "./routes/first-aid/index.tsx": $first_aid_index,
    "./routes/first-aid/print.tsx": $first_aid_print,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/inventory/[id].tsx": $inventory_id_,
    "./routes/inventory/[id]/maintenance.tsx": $inventory_id_maintenance,
    "./routes/inventory/[id]/qr.tsx": $inventory_id_qr,
    "./routes/inventory/[id]/scan.tsx": $inventory_id_scan,
    "./routes/inventory/add.tsx": $inventory_add,
    "./routes/inventory/edit/[id].tsx": $inventory_edit_id_,
    "./routes/inventory/index.tsx": $inventory_index,
    "./routes/loans/index.tsx": $loans_index,
    "./routes/loans/new.tsx": $loans_new,
    "./routes/login.tsx": $login,
    "./routes/meals/[id]/edit.tsx": $meals_id_edit,
    "./routes/meals/index.tsx": $meals_index,
    "./routes/meals/new.tsx": $meals_new,
    "./routes/neckers.tsx": $neckers,
    "./routes/reports/expiring.tsx": $reports_expiring,
    "./routes/risk-assessments/[id]/edit.tsx": $risk_assessments_id_edit,
    "./routes/risk-assessments/index.tsx": $risk_assessments_index,
    "./routes/risk-assessments/print.tsx": $risk_assessments_print,
  },
  islands: {
    "./islands/BackupButtons.tsx": $BackupButtons,
    "./islands/BulkImport.tsx": $BulkImport,
    "./islands/CampCalendar.tsx": $CampCalendar,
    "./islands/CampChecklist.tsx": $CampChecklist,
    "./islands/CampPlanForm.tsx": $CampPlanForm,
    "./islands/CampPlanList.tsx": $CampPlanList,
    "./islands/ConfirmDeleteForm.tsx": $ConfirmDeleteForm,
    "./islands/Counter.tsx": $Counter,
    "./islands/DbCleanup.tsx": $DbCleanup,
    "./islands/DbClear.tsx": $DbClear,
    "./islands/EasterEgg.tsx": $EasterEgg,
    "./islands/FeedbackFormClient.tsx": $FeedbackFormClient,
    "./islands/FeedbackPendingBadge.tsx": $FeedbackPendingBadge,
    "./islands/FeedbackScreenshot.tsx": $FeedbackScreenshot,
    "./islands/FirstAidCheckWizard.tsx": $FirstAidCheckWizard,
    "./islands/FirstAidKitEditor.tsx": $FirstAidKitEditor,
    "./islands/InventoryTable.tsx": $InventoryTable,
    "./islands/ItemDeleteButton.tsx": $ItemDeleteButton,
    "./islands/ItemForm.tsx": $ItemForm,
    "./islands/LoanForm.tsx": $LoanForm,
    "./islands/LoanList.tsx": $LoanList,
    "./islands/MealForm.tsx": $MealForm,
    "./islands/MealPlannerForm.tsx": $MealPlannerForm,
    "./islands/MobileNav.tsx": $MobileNav,
    "./islands/NeckerAlert.tsx": $NeckerAlert,
    "./islands/NeckerCounter.tsx": $NeckerCounter,
    "./islands/NeckerDashboard.tsx": $NeckerDashboard,
    "./islands/NotificationButtons.tsx": $NotificationButtons,
    "./islands/PasswordInput.tsx": $PasswordInput,
    "./islands/PhotoUpload.tsx": $PhotoUpload,
    "./islands/PhotoViewer.tsx": $PhotoViewer,
    "./islands/PrintButton.tsx": $PrintButton,
    "./islands/RebuildIndexes.tsx": $RebuildIndexes,
    "./islands/RestoreBackupForm.tsx": $RestoreBackupForm,
    "./islands/RiskAssessmentForm.tsx": $RiskAssessmentForm,
    "./islands/SpaceDashboard.tsx": $SpaceDashboard,
    "./islands/StocktakeWizard.tsx": $StocktakeWizard,
    "./islands/TemplateAppendForm.tsx": $TemplateAppendForm,
    "./islands/TemplateBuilder.tsx": $TemplateBuilder,
    "./islands/TemplateBulkImport.tsx": $TemplateBulkImport,
    "./islands/ThemeToggle.tsx": $ThemeToggle,
    "./islands/UserDirectory.tsx": $UserDirectory,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
