// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $account_settings from "./routes/account/settings.tsx";
import * as $admin_middleware from "./routes/admin/_middleware.ts";
import * as $admin_activity from "./routes/admin/activity.tsx";
import * as $admin_admin_panel from "./routes/admin/admin-panel.tsx";
import * as $admin_export_json from "./routes/admin/export-json.ts";
import * as $admin_export from "./routes/admin/export.ts";
import * as $admin_import from "./routes/admin/import.ts";
import * as $admin_notify from "./routes/admin/notify.ts";
import * as $admin_rebuild_indexes from "./routes/admin/rebuild-indexes.ts";
import * as $admin_users from "./routes/admin/users.tsx";
import * as $api_camps_id_ from "./routes/api/camps/[id].ts";
import * as $api_camps_index from "./routes/api/camps/index.ts";
import * as $api_items_id_ from "./routes/api/items/[id].ts";
import * as $api_items_index from "./routes/api/items/index.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_logout from "./routes/api/logout.ts";
import * as $api_neckers from "./routes/api/neckers.ts";
import * as $api_ping from "./routes/api/ping.ts";
import * as $api_stats from "./routes/api/stats.ts";
import * as $camps_id_ from "./routes/camps/[id].tsx";
import * as $camps_id_edit from "./routes/camps/[id]/edit.tsx";
import * as $camps_index from "./routes/camps/index.tsx";
import * as $camps_new from "./routes/camps/new.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $inventory_id_ from "./routes/inventory/[id].tsx";
import * as $inventory_add from "./routes/inventory/add.tsx";
import * as $inventory_edit_id_ from "./routes/inventory/edit/[id].tsx";
import * as $inventory_index from "./routes/inventory/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $reports_expiring from "./routes/reports/expiring.tsx";
import * as $BulkImport from "./islands/BulkImport.tsx";
import * as $CampChecklist from "./islands/CampChecklist.tsx";
import * as $CampPlanForm from "./islands/CampPlanForm.tsx";
import * as $CampPlanList from "./islands/CampPlanList.tsx";
import * as $ConfirmDeleteForm from "./islands/ConfirmDeleteForm.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $EasterEgg from "./islands/EasterEgg.tsx";
import * as $InventoryTable from "./islands/InventoryTable.tsx";
import * as $ItemForm from "./islands/ItemForm.tsx";
import * as $MobileNav from "./islands/MobileNav.tsx";
import * as $NeckerAlert from "./islands/NeckerAlert.tsx";
import * as $NeckerCounter from "./islands/NeckerCounter.tsx";
import * as $NotificationButtons from "./islands/NotificationButtons.tsx";
import * as $PasswordInput from "./islands/PasswordInput.tsx";
import * as $RebuildIndexes from "./islands/RebuildIndexes.tsx";
import * as $SpaceDashboard from "./islands/SpaceDashboard.tsx";
import * as $ThemeToggle from "./islands/ThemeToggle.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/account/settings.tsx": $account_settings,
    "./routes/admin/_middleware.ts": $admin_middleware,
    "./routes/admin/activity.tsx": $admin_activity,
    "./routes/admin/admin-panel.tsx": $admin_admin_panel,
    "./routes/admin/export-json.ts": $admin_export_json,
    "./routes/admin/export.ts": $admin_export,
    "./routes/admin/import.ts": $admin_import,
    "./routes/admin/notify.ts": $admin_notify,
    "./routes/admin/rebuild-indexes.ts": $admin_rebuild_indexes,
    "./routes/admin/users.tsx": $admin_users,
    "./routes/api/camps/[id].ts": $api_camps_id_,
    "./routes/api/camps/index.ts": $api_camps_index,
    "./routes/api/items/[id].ts": $api_items_id_,
    "./routes/api/items/index.ts": $api_items_index,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/logout.ts": $api_logout,
    "./routes/api/neckers.ts": $api_neckers,
    "./routes/api/ping.ts": $api_ping,
    "./routes/api/stats.ts": $api_stats,
    "./routes/camps/[id].tsx": $camps_id_,
    "./routes/camps/[id]/edit.tsx": $camps_id_edit,
    "./routes/camps/index.tsx": $camps_index,
    "./routes/camps/new.tsx": $camps_new,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/inventory/[id].tsx": $inventory_id_,
    "./routes/inventory/add.tsx": $inventory_add,
    "./routes/inventory/edit/[id].tsx": $inventory_edit_id_,
    "./routes/inventory/index.tsx": $inventory_index,
    "./routes/login.tsx": $login,
    "./routes/reports/expiring.tsx": $reports_expiring,
  },
  islands: {
    "./islands/BulkImport.tsx": $BulkImport,
    "./islands/CampChecklist.tsx": $CampChecklist,
    "./islands/CampPlanForm.tsx": $CampPlanForm,
    "./islands/CampPlanList.tsx": $CampPlanList,
    "./islands/ConfirmDeleteForm.tsx": $ConfirmDeleteForm,
    "./islands/Counter.tsx": $Counter,
    "./islands/EasterEgg.tsx": $EasterEgg,
    "./islands/InventoryTable.tsx": $InventoryTable,
    "./islands/ItemForm.tsx": $ItemForm,
    "./islands/MobileNav.tsx": $MobileNav,
    "./islands/NeckerAlert.tsx": $NeckerAlert,
    "./islands/NeckerCounter.tsx": $NeckerCounter,
    "./islands/NotificationButtons.tsx": $NotificationButtons,
    "./islands/PasswordInput.tsx": $PasswordInput,
    "./islands/RebuildIndexes.tsx": $RebuildIndexes,
    "./islands/SpaceDashboard.tsx": $SpaceDashboard,
    "./islands/ThemeToggle.tsx": $ThemeToggle,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
