// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $account_settings from "./routes/account/settings.tsx";
import * as $admin_users from "./routes/admin/users.tsx";
import * as $api_items_id_ from "./routes/api/items/[id].ts";
import * as $api_items_index from "./routes/api/items/index.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_logout from "./routes/api/logout.ts";
import * as $api_stats from "./routes/api/stats.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $inventory_id_ from "./routes/inventory/[id].tsx";
import * as $inventory_add from "./routes/inventory/add.tsx";
import * as $inventory_edit_id_ from "./routes/inventory/edit/[id].tsx";
import * as $inventory_index from "./routes/inventory/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $reports_expiring from "./routes/reports/expiring.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $InventoryTable from "./islands/InventoryTable.tsx";
import * as $ItemForm from "./islands/ItemForm.tsx";
import * as $MobileNav from "./islands/MobileNav.tsx";
import * as $PasswordInput from "./islands/PasswordInput.tsx";
import * as $ThemeToggle from "./islands/ThemeToggle.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/account/settings.tsx": $account_settings,
    "./routes/admin/users.tsx": $admin_users,
    "./routes/api/items/[id].ts": $api_items_id_,
    "./routes/api/items/index.ts": $api_items_index,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/logout.ts": $api_logout,
    "./routes/api/stats.ts": $api_stats,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/inventory/[id].tsx": $inventory_id_,
    "./routes/inventory/add.tsx": $inventory_add,
    "./routes/inventory/edit/[id].tsx": $inventory_edit_id_,
    "./routes/inventory/index.tsx": $inventory_index,
    "./routes/login.tsx": $login,
    "./routes/reports/expiring.tsx": $reports_expiring,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/InventoryTable.tsx": $InventoryTable,
    "./islands/ItemForm.tsx": $ItemForm,
    "./islands/MobileNav.tsx": $MobileNav,
    "./islands/PasswordInput.tsx": $PasswordInput,
    "./islands/ThemeToggle.tsx": $ThemeToggle,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
