import { FreshContext } from "$fresh/server.ts";

const JOKES = [
  "I'm reading a book about anti-gravity. It's impossible to put down.",
  "Did you hear about the guy who invented Lifesavers? He made a mint.",
  "I used to hate facial hair, but then it grew on me.",
  "Why can't you hear a pterodactyl go to the bathroom? Because the P is silent.",
  "I'm on a seafood diet. I see food and I eat it.",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "I used to be a banker, but I lost interest.",
  "What do you call cheese that isn't yours? Nacho cheese.",
  "Why don't eggs tell jokes? They'd crack each other up.",
  "I would avoid the sushi if I were you. It's a little fishy.",
  "Want to hear a joke about construction? I'm still working on it.",
  "Why did the bicycle fall over? Because it was two-tired.",
  "What do you call a fish without eyes? A fsh.",
  "I'm afraid for the calendar. Its days are numbered.",
  "Why can't a nose be 12 inches long? Because then it'd be a foot.",
  "What did the ocean say to the beach? Nothing, it just waved.",
  "I only know 25 letters of the alphabet. I don't know y.",
  "What do you call a factory that makes okay products? A satisfactory.",
  "Did you hear about the claustrophobic astronaut? He just needed a little space.",
  "Why did the math book look so sad? Because it had too many problems.",
  "What do you call someone with no body and no nose? Nobody knows.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "What do sprinters eat before a race? Nothing, they fast.",
  "Why did the golfer bring an extra pair of pants? In case he got a hole in one.",
  "How do you organise a space party? You planet.",
  "What do you call a pig that does karate? A pork chop.",
  "Why did the invisible man turn down the job offer? He couldn't see himself doing it.",
  "What do you call a sleeping dinosaur? A dino-snore.",
  "I asked my dog what two minus two is. He said nothing.",
  "Why can't Elsa have a balloon? Because she'll let it go.",
  "What do you call a bear with no teeth? A gummy bear.",
  "I don't trust stairs. They're always up to something.",
  "Why did the tomato turn red? Because it saw the salad dressing.",
  "What do you call a cow with no legs? Ground beef.",
  "I asked a librarian if they had books about paranoia. She whispered 'They're right behind you.'",
  "Why does a chicken coop only have two doors? Because if it had four, it would be a chicken sedan.",
  "What do you call a man with a rubber toe? Roberto.",
  "I used to play piano by ear, but now I use my hands.",
  "What did one hat say to the other? You stay here, I'll go on ahead.",
  "Why did the coffee file a police report? It got mugged.",
  "What do you call a fake noodle? An impasta.",
  "I'm reading a book about teleportation. It's bound to take me somewhere.",
  "What's a vampire's favourite fruit? A blood orange.",
  "Why did the stadium get hot after the game? All the fans left.",
  "Why did the nurse need a red pen at work? In case she needed to draw blood.",
  "How do you make a tissue dance? Put a little boogie in it.",
  "What do you call a dentist who doesn't like tea? Denis.",
  "Why can't you give Elsa a balloon? Because she'll let it go.",
  "I told my doctor I broke my arm in two places. He told me to stop going to those places.",
  "What do you call a belt made of watches? A waist of time.",
  "Why don't scientists trust atoms? Because they make up everything.",
  "I have a joke about paper, but it's tearable.",
  "Did you hear the rumour about butter? Well, I'm not going to spread it.",
  "What did the big flower say to the little flower? Hey, bud!",
];

export const handler = (_req: Request, _ctx: FreshContext): Response => {
  const randomIndex = Math.floor(Math.random() * JOKES.length);
  const body = JOKES[randomIndex];
  return new Response(body);
};
